- .github/pull_request_template.md
- pull_request_template.md
<details open>
<summary> :hand:&nbsp;&nbsp;<strong>Wait!</strong></summary>
Let's make sure your pull request is ready. Ask yourself...
:white_check_mark:&nbsp;&nbsp;"Did I do a good job testing my own code?"
:white_check_mark:&nbsp;&nbsp;"Is my code easy to read and understand?"
:white_check_mark:&nbsp;&nbsp;"Have I written unit tests? Do the unit tests fully cover my code?"
:white_check_mark:&nbsp;&nbsp;"Have I tested the repository's behavior to make sure my code didn't break anything?"
:negative_squared_cross_mark:&nbsp;&nbsp;"Did I include unrelated work that could be in its own pull request?"
Once you are ready, be sure to delete this `details` section before opening your pull request.
</details>
Talk about the intent and scope of the original issue. Go over the general changes that …
> Pull Request Template

- views/browse.slim
This pull request adds the Design System's `m-chat` component.
> Adding `m-chat` component

- catalog-browse.rb
- lib/models/browse_item.rb
- lib/models/browse_list.rb
- lib/utilities/solr_client.rb
- spec/models/browse_list_spec.rb
- views/browse.slim
This adds the logic for showing exact results or no results. It also makes the form work.
This is not well tested.
> Exact result

- public/browse.css
- views/browse.slim
The footer has been restructured and styled, making it a responsive blend between the Search footer and the Design System's `.page-footer`.
This pull request resolves `Success Criteria > 3` in [SEARCH-1524](https://tools.lib.umich.edu/jira/browse/SEARCH-1524).
The copyright originally had `©2018`, which was just static text being used to display the date. I checked the footer in [Search](https://search.lib.umich.edu/everything), and noticed that it has the same information. This pull request pulls in the current date's year. Search's footer will need to be updated.
I don't believe we have established the breakpoints for the site, so for now the footer collapses at `720px`.
The `footer` had a top margin, along with `h1#maincontent`. Together they created the vertical margins for `main`. …
> Responsive Footer

- public/browse.css
- views/browse.slim
This pull request makes the datastores navigation responsive.
> Responsive Datastores

- public/browse.css
- views/browse.slim
In the final stretch of having a responsive site, the search box has been made responsive. Accessibility errors have also been fixed.
This pull request resolves [SEARCH-1524](https://tools.lib.umich.edu/jira/browse/SEARCH-1524).
> Responsive Search Box

- views/components/pagination.erb
- views/layout.erb
This pull request creates a pagination component and adds it to the new layout.
- Check and see if it works.
- Play around with the template to see the changes being made in both areas.
> Pagination Template

- catalog-browse.rb
- lib/models/browse_item.rb
- lib/models/browse_list.rb
- lib/utilities/solr_client.rb
- spec/models/browse_item_spec.rb
- spec/models/browse_list_spec.rb
<details open>
<summary> :hand:&nbsp;&nbsp;<strong>Wait!</strong></summary>
Let's make sure your pull request is ready. Ask yourself...
:white_check_mark:&nbsp;&nbsp;"Did I do a good job testing my own code?"
:white_check_mark:&nbsp;&nbsp;"Is my code easy to read and understand?"
:white_check_mark:&nbsp;&nbsp;"Have I written unit tests? Do the unit tests fully cover my code?"
:white_check_mark:&nbsp;&nbsp;"Have I tested the repository's behavior to make sure my code didn't break anything?"
:negative_squared_cross_mark:&nbsp;&nbsp;"Did I include unrelated work that could be in its own pull request?"
Once you are ready, be sure to delete this `details` section before opening your pull request.
</details>
Talk about the intent and scope of the original issue. Go over the general changes that …
> Exact matches

- lib/models/browse_list.rb
Actually does the thing. Forgot to commit most recent changes"
> actually does the match index stuff

- catalog-browse.rb
- lib/models/search_dropdown.rb
- lib/utilities/solr_client.rb
- views/layout.erb
Implements search dropdown. 
Not tested and needs refactoring. This will be straightforward.
> Search dropdown

- .env-example
- README.md
- lib/utilities/solr_client.rb
Adds environment variable for callnumbers core
> uses environment variable for callnumber solr core

- lib/utilities/solr_client.rb
- spec/requests_spec.rb
- spec/spec_helper.rb
Fixes bug in SolrClient for browse_reference_on_top Also adds some request specs.
> More tests

- catalog-browse.rb
- lib/models/browse_list.rb
- spec/models/browse_list_spec.rb
Adds a banner_reference url parameter to keep track of where the banner should go on the first page of results.
- Run the tests to make sure they pass 
```
docker-compose run --rm web bundle exec rspec
```
- _How to use the feature_.
> Banner fix

- .env-dev-values
- docker-compose.yml
- lib/models/browse_list.rb
- lib/models/search_dropdown.rb
- spec/models/browse_list_spec.rb
- spec/models/search_dropdown_spec.rb
Adding explicit base url as an enivornment variable.
> changed urls to use full url

- .env-example
- README.md
- lib/utilities/solr_client.rb
- spec/requests_spec.rb
- spec/spec_helper.rb
Hotfix so it uses production catalog solr.
> Use production catalog solr

- .env-dev-values
- catalog-browse.rb
- config/datastores.yml
- lib/models/datastores.rb
- lib/models/search_dropdown.rb
- spec/models/datastores_spec.rb
- views/layout.erb
Added a SEARCH_URL environment variable to enable switching which version of search browse links to. 
To test:
`docker-compose run --rm web bundle exec rspec`
> Fixes Search Dropdown in Browse

- views/layout.erb
Google Analytics has been added to the layout.
This pull request resolves [JIRA-1546](https://tools.lib.umich.edu/jira/browse/JIRA-1546).
> [SEARCH-1546] Google Analytics event tracking

- views/layout.erb
The analytics added to the site did not cover certain events because the events have not been created. This pull request adds Google's generated scripts, and also scripts for tracking custom events.
This pull request resolves:
* [SEARCH-1567](https://tools.lib.umich.edu/jira/browse/SEARCH-1567)
* [SEARCH-1568](https://tools.lib.umich.edu/jira/browse/SEARCH-1568)
* [SEARCH-1569](https://tools.lib.umich.edu/jira/browse/SEARCH-1569)
* [SEARCH-1570](https://tools.lib.umich.edu/jira/browse/SEARCH-1570)
> [SEARCH-1565] Google Event Tag Manager and Hotjar Tracking

- catalog-browse.rb
- lib/utilities/string_cleaner.rb
- spec/utilities/string_cleaner_spec.rb
This fixes the bug where quote subject search strings would result in an error.
> cleans up string

- css/browse.css
- css/styles/cross-references.css
- css/styles/description-list.css
- css/styles/table.css
- css/styles/typography.css
- lib/models/subject_item.rb
- spec/models/subject_item_spec.rb
- views/subject.erb
This pull request resolves/closes/fixes [LIBSEARCH-864](https://mlit.atlassian.net/browse/LIBSEARCH-864).
List instructions on how to test the pull request. Some examples:
- _How to use the feature_.
> Libsearch 864 cross references toggle terms

- .github/dependency_update_template.md
- .github/workflows/dependency-update.yml
Adds workflow for creating a monthly pr for dependency updates.
> add auto update workflow

- .github/workflows/dependency-update.yml
Fixing the space bug from the previous pr
> Fix: Fixing the spacing bug of the previous update-dependencies pr

- lib/models/subject_item.rb
- spec/fixtures/subject_results.json
- spec/models/subject_item_spec.rb
This PR has some refactoring to enable adding another kind of subject cross reference.
> handles SeeInstead xref

- lib/services.rb
- views/layout.erb
See this PR: https://github.com/mlibrary/account/pull/319
> adds version meta tag
