mlibrary/search.catalog-browse

public/browse.css
While working on the [Figma components](https://www.figma.com/file/ymqm7jMhh1xFIONkNZZrcB/?node-id=228%3A9142), I realized the order from lightest to darkest was out of place between `var(--search-neutral-100)` and `var(--search-neutral-200)`.
_Left: Previous order. Right: New order._
This pull request updates that order.
I was unsuccessful in trying to pull up [http://localhost:4567/](http://localhost:4567/) to test it, so I had to make tests within the browser to see if my changes worked.
=> Swapping `neutral` root variables

public/browse.css, views/browse.slim
This pull request updates the pagination to look more like the [Figma design](https://www.figma.com/file/ymqm7jMhh1xFIONkNZZrcB/?node-id=0%3A9201).
The pagination has been converted to an unordered list, and has been given a `.pagination` class to cover the styles. `m-icon` components have been added to create the left/right arrows.
=> Updating pagination layout and styles

public/browse.css, views/browse.slim
In an effort to increase accessibility, a "Skip links" section has been added. It contains two links:
* Skip to main content (takes you to the `h1`)
* Skip to Ask a Librarian chat (takes you to `m-chat`)
- Tab through section and click on the links
- Does it appear when you tab to it?
- Does it disappear when you tab out of it?
- Does `Skip to main content` direct you to the `h1`?
- Does `Skip to Ask a Librarian chat` direct you to the `m-chat`?
=> Adding skip links section and styles

public/browse.css, views/browse.slim
Responsive styles have been added to the `table` containing browse results.
This pull request resolves `Success Criteria > 1` of [SEARCH-1524](https://tools.lib.umich.edu/jira/browse/SEARCH-1524).
The Design System's `.m-table` styles have not yet been pushed to https://unpkg.com/@umich-lib/web@1.2.1/umich-lib.css, so interim styles have been added. 
The `result.match_notice?` row and fields have been restructured for styling and to reduce repeated code. The notice does not show up for me, even when viewing on `main`, so I wasn't not able to fully test.
=> Responsive Table

public/browse.css, views/browse.slim
Reimplement the Library Search Website Header in the Catalog Browse Website Header since that needs to be recreated because Catalog Browse is it's own Sinatra app.
This pull request will close: https://tools.lib.umich.edu/jira/browse/SEARCH-1525
Small viewport: https://user-images.githubusercontent.com/1678665/143902489-237bae39-2638-4458-9881-6789ef672ec5.png
Large viewport: https://user-images.githubusercontent.com/1678665/143902506-f1eb3517-ce16-40a0-afa2-a4ad2548bf5a.png
=> SEARCH-1525: Catalog Browse Header Content

public/browse.css, views/layout.erb
This pull request updates the styling of exact matches according to the [Figma design](https://www.figma.com/file/ymqm7jMhh1xFIONkNZZrcB/?node-id=0%3A9201).
I have changed the media queries so it is now mobile-first.
=> Exact match styling

public/browse.css, views/layout.erb
This pull request changes the media queries for `.search-box` and `.datastores-nav` to be mobile-first.
=> Mobile first media queries

views/layout.erb
This hotfix changes the action to the form to include the `ENV['BASE_URL']`.
=> Fix for form action.

config/search_dropdown.yml, lib/models/search_dropdown.rb, public/browse.css, public/browse.js, spec/models/search_dropdown_spec.rb, views/layout.erb
When a user selects an option from the dropdown menu, a tip will appear under the form to help show the user how to properly search or browse for an item. This tip will appear under the search form.
This pull request resolves the `Catalog` portion of [SEARCH-1505](https://tools.lib.umich.edu/jira/browse/SEARCH-1505).
Browse now has updated text that is inclusive of Dewey call numbers.
This pull request resolves the `Catalog` portion of [SEARCH-1538](https://tools.lib.umich.edu/jira/browse/SEARCH-1538).
The back-ticks that surround the call number have been changed to double-quotes.
This pull request resolves [SEARCH-1539](https://tools.lib.umich.edu/jira/browse/SEARCH-1539).
To lessen future work, the remaining upcoming browse options have been added to the dropdown. The [tips are still …
=> [SEARCH-1505] Add search hint/help suggestions to the Catalog Browse UI

public/browse.css, views/layout.erb
In an effort to mirror Catalog with Search, a `Give feedback about this page` link has been added to the bottom of the layout.
This pull request resolves [JIRA-1540](https://tools.lib.umich.edu/jira/browse/JIRA-1540).
=> [SEARCH-1540] Add standard Library Search feedback link to bottom of browse pages

views/layout.erb
The heading and [help text](https://docs.google.com/document/d/1miNSN1rRqO6xsbS88u-b582E77sCEgciDaozmUmZ4Ys/edit?usp=sharing) has been updated.
This pull request resolves [JIRA-1543](https://tools.lib.umich.edu/jira/browse/JIRA-1543).
=> [SEARCH-1543] Update heading and help text on Call Number Browse landing page

lib/models/browse_item.rb, public/browse.css, spec/models/browse_item_spec.rb, views/layout.erb
Each browse item will now display the vernacular data next to its transliterated data. All data (except the title) will now have a label next to it, to match the [Figma design](https://www.figma.com/file/ymqm7jMhh1xFIONkNZZrcB/?node-id=381%3A9747).
This pull request resolves/closes/fixes [JIRA-1533](https://tools.lib.umich.edu/jira/browse/JIRA-1533).
SEARCH-1533 also lists adding `Series` in this issue, but the data doesn't get added until [JIRA-1534](https://tools.lib.umich.edu/jira/browse/JIRA-1534).
- Look up a call number with vernacular …
=> [SEARCH-1533] Show both transliterated and vernacular data where it is available

lib/models/browse_item.rb, spec/models/browse_item_spec.rb, views/layout.erb
Series and its vernacular equivalent will now be added to the list of data for each browse item.
This pull request resolves/closes/fixes [JIRA-1534](https://tools.lib.umich.edu/jira/browse/JIRA-1534).
- Browse for a call number to see `Series` information show up (e.g. `PQ 1852 .B85 1992`)
=> [SEARCH-1534] Add display of series information

config/search_dropdown.yml
The browse tip contained redundant information and needed to be updated, according to [the document](https://docs.google.com/document/d/1BtG67b41-KxX5wnDE3bI1EJ6THZPHFkOOcBSMqRDSls/edit?usp=sharing).
This pull request resolves/closes/fixes [JIRA-1545](https://tools.lib.umich.edu/jira/browse/JIRA-1545).
=> [SEARCH-1545] Update CNB drop-down selection Browse Tip to match revised specification

config/search_dropdown.yml
The tips contained some typos, mainly based on period placements.
This pull request resolves [SEARCH-1564](https://tools.lib.umich.edu/jira/browse/SEARCH-1564).
Search's dropdown has `[BETA]` after `Browse by call number (LC and Dewey)`, so it has also been added here to match.
- On [localhost](http://localhost:4567/callnumber), check the tip under the search form.
- Does the tip for the default selected option appear on load?
- When you select a different option, does the tip change?
- Does the tip change when you try to select a disabled option?
=> [SEARCH-1564] Browse Tip Typos

css/styles/table.css, views/layout.erb
Using pipes (`|`) as a separator for the vernacular information gave a `specialCharacterUsed` warning in ARC Toolkit. In order to remove it, the character has been replaced with a custom `:before` element based on the `.vernacular.pipe` class.
=> Removing `specialCharacterUsed` ARC Toolkit Warning

catalog-browse.rb, config/search_dropdown.yml, css/styles/anchors.css, css/styles/table.css, lib/models/browse_list.rb, lib/models/fake_authors.rb, package-lock.json, package.json, postcss.config.js, spec/models/browse_list_spec.rb, views/authors.erb, views/call_number.erb, views/components/pagination.erb, views/layout.erb, views/layout/datastore_navigation.erb, views/layout/search_box.erb
The fake data is up for `Browse by author`, and the site needs help in displaying it similar to `Browse by call number (LC and Dewey)`.
This pull request resolves [SEARCH-1604](https://tools.lib.umich.edu/jira/browse/SEARCH-1604).
`./views/layout.erb` has been broken up so it now it acts a template for other browse options.
`cssnano` has been added to help minify the built stylesheet so it doesn't get bloated with all of the documentation.
- Build the CSS (`docker-compose run --rm web npm run build`).
- Go to [Browse by author](http://localhost:4567/author) and see...
- If the information is displayed.
- The website …
=> [SEARCH-1604] Implement design for author browse

package-lock.json, package.json
Updating `npm` dependencies for the sake of security.
This needs to be a monthly task.
[`chokidar-cli`](https://www.npmjs.com/package/chokidar-cli) had several vulnerabilities, and has not been updated in 8 months. There is an [issue](https://github.com/open-cli-tools/chokidar-cli/issues/105) that has been open for a few months to fix it. The package is only used to watch CSS changes, which is nice but is not required for development. I have made the decision to remove it.
* Remove and install packages (`rm -rf node_modules/ && docker-compose run --rm web npm install`).
* Launch the [site](http://localhost:4567/callnumber?query=UM1) and see if everything looks good.
* Trying and build the css (`docker-compose run --rm web npm run build`).
=> Updating dependencies and removing chokidar-cli

lib/models/browse_item.rb, spec/fixtures/zhizn_bib.json
The Solr field displaying `Series` information has changed from `series` to `series_statement`. This pull request updates the information and related tests.
This pull request closes [SEARCH-1697](https://tools.lib.umich.edu/jira/browse/SEARCH-1697).
- Run the tests to make sure they pass (`docker-compose run web bundle exec rspec`).
- Browse for an item that has `Series`, and see if it displays. (e.g. [PQ 1852 .B85 1992](http://localhost:4567/callnumber?query=PQ+1852+.B85+1992))
=> [SEARCH-1697] Add "series statement" Solr field to call number browse display after Published field

config/search_dropdown.yml
> "Academic Discipline" option in the Catalog Search field menu is also a filter. This redundancy is not useful and is rarely used.
This pull request closes [LIBSEARCH-711](https://mlit.atlassian.net/browse/LIBSEARCH-711).
- Use the dropdown menu and see if `Academic Discipline` does not show.
=> [LIBSEARCH-711] Remove "Academic Discipline" from Catalog Search drop-down menus

css/styles/anchors.css, css/styles/base.css, css/styles/datastores-navigation.css, css/styles/m-website-header.css, css/styles/pagination.css, css/styles/search-box.css, css/styles/skip-links.css, css/styles/table.css, css/styles/typography.css, views/components/pagination.erb, views/layout.erb, views/layout/search_box.erb
The Design System is deprecating the `m-icon` component and all `space` variables. This pull request replaces all of the components with [Material Icons](https://fonts.google.com/icons), and the variables with the equivalent of `rem` measurements according to the [design tokens](https://design-system.lib.umich.edu/design-tokens/#space).
- Compare [development](http://localhost:4567/callnumber?query=PQ+1852+.B85+1992) to [production](https://search.lib.umich.edu/catalog/browse/callnumber?query=PQ+1852+.B85+1992).
- Do they look the same?
=> Design system cleanup

docker-compose.yml
On `docker-compose up`, it produced the message:
```bash
css_1  | npm ERR! Missing script: "watch"
```
This is because under the `css` service, `npm run watch` was being called. The script was removed after the `chokidar-cli` package was [uninstalled](https://github.com/mlibrary/catalog-browse/commit/ec6e5b67a14390f60cf99cc5020aad42fa02c079). Since `web` contains the same data, the `css` service has been removed.
- Rebuild and run Docker.
- Does it still launch?
- Can you still make CSS updates?
=> Bug: Removing `css` Service

lib/models/author_item.rb, views/authors.erb
`(catalog results)` and `(in author list)` were being queried when you clicked on the link. This pull request separates the link text from the author so only the author itself is queried.
List instructions on how to test the pull request. Some examples:
- Check the links to see if search and browse are looking at the correct queries.
=> Bug: Separating author and link text

catalog-browse.rb, views/layout.erb
A feedback form exists for Author browse. It has now been added to `m-callout` by adding a `feedback_url` local variable. If the variable is not defined, it defaults to the feedback form that is also linked at the bottom.
- [Browse by author](http://localhost:4567/author?query=smith).
- Are you linked to the new [survey](https://umich.qualtrics.com/jfe/form/SV_43jm8oGIRVLEBbo) in the callout?
- [Browse by callnumber](http://localhost:4567/callnumber?query=UM1).
- Are you linked to the default [survey](https://umich.qualtrics.com/jfe/form/SV_bCwYIKueEXs8wBf) in the callout?
=> Adding `feedback_url` option for `m-callout`

lib/models/author_item.rb, views/authors.erb
Removing ` (catalog results)` from the link label has shown to improve readability, according to UX research.
This pull request resolves [LIBSEARCH-776](https://mlit.atlassian.net/browse/LIBSEARCH-776).
- Browse an [author](http://localhost:4567/author?query=Twain%2C+Mark)
- Does ` (catalog results)` show in the main author link?
- Do you still see ` (in author list)` in cross references?
=> [LIBSEARCH-776] Remove (catalog results) from Main author links in Author browse

lib/models/author_list.rb
The Author Browse help text has been updated to improve clarity, based on UX research.
This pull request resolves [LIBSEARCH-777](https://mlit.atlassian.net/browse/LIBSEARCH-777).
- Browse an [author](http://localhost:4567/author?query=Twain%2C+Mark)
- Under the `Browse [author] in authors` title, does it say:
```
Browse by author help: Search an author (last names, first name), organization or conference and view an alphabetical list of all author headings that link to matching records in the library catalog. Also view variations of some author names (pseudonyms) linked to that part of the author index.
```
=> [LIBSEARCH-777] Update "Browse by author help" text in Author browse index views

lib/models/browse_list_presenter.rb
Replacing `Browse “Author name” in authors` with `Browse “Author name” in an alphabetical list of authors` when browing in `author`.
This pull request closes [LIBSEARCH-779](https://mlit.atlassian.net/browse/LIBSEARCH-779).
- [Browse by author](http://localhost:4567/author?query=Twain%2C+Mark)
- Does it say `Browse “Author name” in an alphabetical list of authors`?
- [Browse by callnumber](http://localhost:4567/callnumber?query=UM1)
- Does it say `Browse “Call number” in call numbers`?
=> [LIBSEARCH-779] Update h1 Label in Catalog Browse: Browse by Author views. 

catalog-browse.rb, lib/models/author_list.rb, lib/models/browse_list_presenter.rb, lib/models/callnumber_list.rb, package-lock.json, spec/models/author_list_spec.rb, spec/models/browse_list_presenter_spec.rb, spec/models/callnumber_list_spec.rb, views/layout.erb
According to [Browse Punchlist -- Feedback, Bugs, Suggestions, etc.](https://docs.google.com/spreadsheets/d/1r2G8XfJwrGMOL4hKoV-_O7fPv17SIKHzdzAT4bZamEg/edit?usp=sharing):
> Page title(s) in Author Browse are "Search | Browse by Call Number (Library of Congress and Dewey)" when they should be "Search | Browse by Author"
This pull request creates a `title` local variable that allows the `<title>` to be set for each view.
- Browse by call number.
- Does the title read `Library Search | Browse by Call Number (Library of Congress and Dewey)`?
- Browse by author.
- Does the title read `Library Search | Browse by Author`?
=> Adding `title` variable

views/layout.erb
Design System was using `unpkg` for their CDN, but has since been unsupported. They are now switching to `jsDelivr`.
This pull request updates the new CDN.
- Check the website and see if anything looks broken.
=> [DS-120] Update properties to jsDelivr

views/layout/search_box.erb
Fixes a bug where the drop down shows "Browse by Author" as an option even though it's not available yet. 
This PR turns it off if `AUTHOR_ON == "false"`
=> adds logic to turn off browse by author

config/search_dropdown.yml
Takes out "Browse by title" as a coming soon disabled option in the dropdown.
=> removes browse by title as coming soon

catalog-browse.rb, lib/utilities/string_cleaner.rb, spec/utilities/string_cleaner_spec.rb
This removes unnecessary (to browse) characters from the user-submitted author string before setting the `reference_id` which is then sent to `AuthorList.for`.
I'm not at all sure how to test this. Would love to be taught.
=> Clean up the user-submitted author browse string

views/subject.erb
The label `Use instead of` is confusing for broader term results. Changing it to `Broader Term(s)` aligns with the `Narrower Term(s)` label, and is more straightforward.
=> fix: Replacing `Use instead of` with `Broader Term(s)`

lib/models/author_item.rb, lib/models/browse_list_presenter.rb, lib/models/subject_item.rb
> Update h1 to be: Browse [search term] in alphabetical list of subjects
This title now applies to all browse options that are not `call number`.
> Can we make “records” singular for 1-record entries?
The logic was there, but was being compared to the incorrect type. `count` returns a string, and being compared to a number. The number has been converted to a string.
- See if `1 record` will show up for a [cross reference](http://localhost:4567/subject?query=Peatland+management).
- See if [subject browse] now says `Browse “[term]” in an alphabetical list of subjects`.
=> 2023-03-23 Meeting

css/styles/m-callout.css, views/components/harmful_language_statement.erb, views/layout.erb
This pull request adds an `m-callout` component that contains a statement about remediating harmful language. It will only show in Subject browse.
This pull request closes [LIBSEARCH-872](https://mlit.atlassian.net/browse/LIBSEARCH-872).
- Build and run the site. Check and see if the statement only shows in Subject browse. Does it also show while navigating through the pagination?
=> [LIBSEARCH-872] Add "remediation of harmful subjects" language to subject browse pages

css/styles/cross-references.css, css/styles/table.css, views/subject.erb
There were two UI-related issues that need improvement:
1. Terms are found to be difficult to distinguish between the bolded headings. To fix this, the list of cross references has been indented.
2. On mobile, the total number of records for a subject entry moves to the bottom of the display and can be hidden if there are a lot of cross references. The number of records now appear under the subject on mobile.
This pull request resolves [LIBSEARCH-876](https://mlit.atlassian.net/browse/LIBSEARCH-876).
- Build the styles and run the site.
- Do the records appear directly under the subject on mobile?
- Are the list of cross references indented?
=> [LIBSEARCH-876] Update display of long subject lists in Subject Browse

views/layout.erb
Favorites has been retired, so the `My Favorites` link is no longer useful and has been removed.
`Account` has also been rebuilt and has a new URL, so the link has been updated.
=> Updating `m-website-header` links.

views/layout.erb
> We migrated to a new GTM Container and we need to update the tracking code for Catalog browse (it’s not collecting data because it has the old tracking code and GTM tracking ID.
=> [LIBSEARCH-888] Update Google Tag Manager Tracking Code in Catalog Browse views

lib/models/callnumber_item.rb, spec/models/callnumber_item_spec.rb
Callnumber browse items that don't have a corresponding record in catalog solr were causing the site to break. This situation can happen when an item has been deleted in Alma, but the callnumber browse index is out of date. 
The temporary solution is to print nothing for the title in the list.
=> fix: callnumber browse items without a catlog record

Gemfile.lock, package-lock.json, package.json
Monthly dependency update to help maintain Catalog Browse.
These dependencies have been updated to their latest versions:
- `postcss`
Highlights of gem updates
- `puma`
- `faraday`
- Install the updated packages (`docker-compose run --rm web npm install`).
- Make a CSS change, and build the styles (`docker-compose run --rm web npm run build`).
- Start [the site](http://localhost:4567/callnumber?query=UM1) to see if your change was made, and everything still works (`docker-compose up`).
=> October 2023 dependency updates.

Gemfile, Gemfile.lock, catalog-browse.rb, env.example, lib/models/author_list.rb, lib/services.rb, lib/utilities/browse_solr_client.rb, spec/spec_helper.rb
This PR enables the optional use of solr cloud for author browse. If the environment variable `SOLR_CLOUD_ON` is true then  `BrowseSolrClient` will try to use basic auth when connecting to solr. 
To make this change easier, Canister has been added to handle environment variables.
For tests `S.solr_cloud_on?` is set to false and the assumption is all browse solr urls are the same.
=> solr cloud for authors is optional

Gemfile, Gemfile.lock, catalog-browse.rb, lib/services.rb, spec/spec_helper.rb
There was a deprecation warning for `Rack::Logger`. This PR replaces `Rack::Logger` with Semantic Logger.
=> Replaces Rack::Logger for Sinatra's logger

views/layout.erb
m-chat has had an updated skin in the old Design System repository. To make sure the CDN is always up to date, the version has been updated to latest. The CDN will be replaced when the new Design System is ready for launch.
=> change design-system to pull latest version

catalog-browse.rb
Code provided by @bertrama:
```
diff --git a/catalog-browse.rb b/catalog-browse.rb
index 3e68331..47c11c9 100644
--- a/catalog-browse.rb
+++ b/catalog-browse.rb
@@ -23,6 +23,7 @@ require_relative "lib/models/search_dropdown"
require_relative "lib/models/datastores"
set :logger, S.logger
+set :protection, except: [:json_csrf]
CatalogSolrClient.configure do |config|
config.solr_url = S.biblio_solr
```
=> Adding `set` to resolve: `web_1  | W, [2024-07-31T15:53:28.302636 #1]  WARN -- : attack prevented by Rack::Protection::JsonCsrf`

lib/models/carousel_list.rb, spec/models/carousel_list_spec.rb
Search has access to Syndetic Solutions book cover API until November 28. In order to pull the images, we need access to the record's `isbn`, `issn`, and/or `oclc` data. This pull request adds those fields to the carousel API.
This pull request fixes [LIBSEARCH-1032](https://mlit.atlassian.net/browse/LIBSEARCH-1032).
=> [LIBSEARCH-1032] Test an integration of book covers from Syndetic Solutions in the shelf carousel

.github/dependabot.yml, .github/workflows/dependabot.yml
Adds second dependency group for Dockerfile and docker-compose because we only want to update those yearly. We also don't want those to auto-merge because tests will not automatically catch changes due to the image change because the tests GHA won't get an automated ruby version update.
Also changes from cron to monthly for interval for app-dependencies group. 
Also goes back to checking for PR updates. Status checks are required in the branch rules.
=> Container-updates group
